<<<<<<< HEAD
﻿//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Tutopt.Models.Storage
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EntityStorage : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EntityStorage object using the connection string found in the 'EntityStorage' section of the application configuration file.
        /// </summary>
        public EntityStorage() : base("name=EntityStorage", "EntityStorage")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EntityStorage object.
        /// </summary>
        public EntityStorage(string connectionString) : base(connectionString, "EntityStorage")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EntityStorage object.
        /// </summary>
        public EntityStorage(EntityConnection connection) : base(connection, "EntityStorage")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Goods> Goods
        {
            get
            {
                if ((_Goods == null))
                {
                    _Goods = base.CreateObjectSet<Goods>("Goods");
                }
                return _Goods;
            }
        }
        private ObjectSet<Goods> _Goods;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Goods EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGoods(Goods goods)
        {
            base.AddObject("Goods", goods);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="uh252489_dbModel", Name="Goods")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Goods : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Goods object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="article">Initial value of the Article property.</param>
        /// <param name="categoryId">Initial value of the CategoryId property.</param>
        /// <param name="shortInformation">Initial value of the ShortInformation property.</param>
        /// <param name="fullInformation">Initial value of the FullInformation property.</param>
        /// <param name="purchasePrice">Initial value of the PurchasePrice property.</param>
        /// <param name="maxPrice">Initial value of the MaxPrice property.</param>
        /// <param name="middlePrice">Initial value of the MiddlePrice property.</param>
        /// <param name="minPrie">Initial value of the MinPrie property.</param>
        /// <param name="count">Initial value of the Count property.</param>
        /// <param name="imageId">Initial value of the ImageId property.</param>
        /// <param name="isWarranty">Initial value of the IsWarranty property.</param>
        /// <param name="warranty">Initial value of the Warranty property.</param>
        /// <param name="statusId">Initial value of the StatusId property.</param>
        public static Goods CreateGoods(global::System.Int32 id, global::System.String name, global::System.String article, global::System.Int32 categoryId, global::System.String shortInformation, global::System.String fullInformation, global::System.Decimal purchasePrice, global::System.Decimal maxPrice, global::System.Decimal middlePrice, global::System.Decimal minPrie, global::System.Int32 count, global::System.Int32 imageId, global::System.Boolean isWarranty, global::System.Int16 warranty, global::System.Int16 statusId)
        {
            Goods goods = new Goods();
            goods.Id = id;
            goods.Name = name;
            goods.Article = article;
            goods.CategoryId = categoryId;
            goods.ShortInformation = shortInformation;
            goods.FullInformation = fullInformation;
            goods.PurchasePrice = purchasePrice;
            goods.MaxPrice = maxPrice;
            goods.MiddlePrice = middlePrice;
            goods.MinPrie = minPrie;
            goods.Count = count;
            goods.ImageId = imageId;
            goods.IsWarranty = isWarranty;
            goods.Warranty = warranty;
            goods.StatusId = statusId;
            return goods;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Article
        {
            get
            {
                return _Article;
            }
            set
            {
                OnArticleChanging(value);
                ReportPropertyChanging("Article");
                _Article = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Article");
                OnArticleChanged();
            }
        }
        private global::System.String _Article;
        partial void OnArticleChanging(global::System.String value);
        partial void OnArticleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CategoryId
        {
            get
            {
                return _CategoryId;
            }
            set
            {
                OnCategoryIdChanging(value);
                ReportPropertyChanging("CategoryId");
                _CategoryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CategoryId");
                OnCategoryIdChanged();
            }
        }
        private global::System.Int32 _CategoryId;
        partial void OnCategoryIdChanging(global::System.Int32 value);
        partial void OnCategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ShortInformation
        {
            get
            {
                return _ShortInformation;
            }
            set
            {
                OnShortInformationChanging(value);
                ReportPropertyChanging("ShortInformation");
                _ShortInformation = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ShortInformation");
                OnShortInformationChanged();
            }
        }
        private global::System.String _ShortInformation;
        partial void OnShortInformationChanging(global::System.String value);
        partial void OnShortInformationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FullInformation
        {
            get
            {
                return _FullInformation;
            }
            set
            {
                OnFullInformationChanging(value);
                ReportPropertyChanging("FullInformation");
                _FullInformation = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FullInformation");
                OnFullInformationChanged();
            }
        }
        private global::System.String _FullInformation;
        partial void OnFullInformationChanging(global::System.String value);
        partial void OnFullInformationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PurchasePrice
        {
            get
            {
                return _PurchasePrice;
            }
            set
            {
                OnPurchasePriceChanging(value);
                ReportPropertyChanging("PurchasePrice");
                _PurchasePrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PurchasePrice");
                OnPurchasePriceChanged();
            }
        }
        private global::System.Decimal _PurchasePrice;
        partial void OnPurchasePriceChanging(global::System.Decimal value);
        partial void OnPurchasePriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MaxPrice
        {
            get
            {
                return _MaxPrice;
            }
            set
            {
                OnMaxPriceChanging(value);
                ReportPropertyChanging("MaxPrice");
                _MaxPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxPrice");
                OnMaxPriceChanged();
            }
        }
        private global::System.Decimal _MaxPrice;
        partial void OnMaxPriceChanging(global::System.Decimal value);
        partial void OnMaxPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MiddlePrice
        {
            get
            {
                return _MiddlePrice;
            }
            set
            {
                OnMiddlePriceChanging(value);
                ReportPropertyChanging("MiddlePrice");
                _MiddlePrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MiddlePrice");
                OnMiddlePriceChanged();
            }
        }
        private global::System.Decimal _MiddlePrice;
        partial void OnMiddlePriceChanging(global::System.Decimal value);
        partial void OnMiddlePriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MinPrie
        {
            get
            {
                return _MinPrie;
            }
            set
            {
                OnMinPrieChanging(value);
                ReportPropertyChanging("MinPrie");
                _MinPrie = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MinPrie");
                OnMinPrieChanged();
            }
        }
        private global::System.Decimal _MinPrie;
        partial void OnMinPrieChanging(global::System.Decimal value);
        partial void OnMinPrieChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Count
        {
            get
            {
                return _Count;
            }
            set
            {
                OnCountChanging(value);
                ReportPropertyChanging("Count");
                _Count = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Count");
                OnCountChanged();
            }
        }
        private global::System.Int32 _Count;
        partial void OnCountChanging(global::System.Int32 value);
        partial void OnCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ImageId
        {
            get
            {
                return _ImageId;
            }
            set
            {
                OnImageIdChanging(value);
                ReportPropertyChanging("ImageId");
                _ImageId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ImageId");
                OnImageIdChanged();
            }
        }
        private global::System.Int32 _ImageId;
        partial void OnImageIdChanging(global::System.Int32 value);
        partial void OnImageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsWarranty
        {
            get
            {
                return _IsWarranty;
            }
            set
            {
                OnIsWarrantyChanging(value);
                ReportPropertyChanging("IsWarranty");
                _IsWarranty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsWarranty");
                OnIsWarrantyChanged();
            }
        }
        private global::System.Boolean _IsWarranty;
        partial void OnIsWarrantyChanging(global::System.Boolean value);
        partial void OnIsWarrantyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Warranty
        {
            get
            {
                return _Warranty;
            }
            set
            {
                OnWarrantyChanging(value);
                ReportPropertyChanging("Warranty");
                _Warranty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Warranty");
                OnWarrantyChanged();
            }
        }
        private global::System.Int16 _Warranty;
        partial void OnWarrantyChanging(global::System.Int16 value);
        partial void OnWarrantyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 StatusId
        {
            get
            {
                return _StatusId;
            }
            set
            {
                if (_StatusId != value)
                {
                    OnStatusIdChanging(value);
                    ReportPropertyChanging("StatusId");
                    _StatusId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StatusId");
                    OnStatusIdChanged();
                }
            }
        }
        private global::System.Int16 _StatusId;
        partial void OnStatusIdChanging(global::System.Int16 value);
        partial void OnStatusIdChanged();

        #endregion

    
    }

    #endregion

    
}
=======
﻿//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Tutopt.Models.Storage
{
    #region Контексты
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    public partial class EntityStorage : ObjectContext
    {
        #region Конструкторы
    
        /// <summary>
        /// Инициализирует новый объект EntityStorage, используя строку соединения из раздела "EntityStorage" файла конфигурации приложения.
        /// </summary>
        public EntityStorage() : base("name=EntityStorage", "EntityStorage")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта EntityStorage.
        /// </summary>
        public EntityStorage(string connectionString) : base(connectionString, "EntityStorage")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта EntityStorage.
        /// </summary>
        public EntityStorage(EntityConnection connection) : base(connection, "EntityStorage")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Разделяемые методы
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Свойства ObjectSet
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<Goods> Goods
        {
            get
            {
                if ((_Goods == null))
                {
                    _Goods = base.CreateObjectSet<Goods>("Goods");
                }
                return _Goods;
            }
        }
        private ObjectSet<Goods> _Goods;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<Orders> Orders
        {
            get
            {
                if ((_Orders == null))
                {
                    _Orders = base.CreateObjectSet<Orders>("Orders");
                }
                return _Orders;
            }
        }
        private ObjectSet<Orders> _Orders;

        #endregion

        #region Методы AddTo
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet Goods. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToGoods(Goods goods)
        {
            base.AddObject("Goods", goods);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet Orders. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToOrders(Orders orders)
        {
            base.AddObject("Orders", orders);
        }

        #endregion

    }

    #endregion

    #region Сущности
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="uh252489_dbModel", Name="Goods")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Goods : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта Goods.
        /// </summary>
        /// <param name="id">Исходное значение свойства Id.</param>
        /// <param name="name">Исходное значение свойства Name.</param>
        /// <param name="article">Исходное значение свойства Article.</param>
        /// <param name="categoryId">Исходное значение свойства CategoryId.</param>
        /// <param name="shortInformation">Исходное значение свойства ShortInformation.</param>
        /// <param name="fullInformation">Исходное значение свойства FullInformation.</param>
        /// <param name="purchasePrice">Исходное значение свойства PurchasePrice.</param>
        /// <param name="maxPrice">Исходное значение свойства MaxPrice.</param>
        /// <param name="middlePrice">Исходное значение свойства MiddlePrice.</param>
        /// <param name="minPrie">Исходное значение свойства MinPrie.</param>
        /// <param name="count">Исходное значение свойства Count.</param>
        /// <param name="imageId">Исходное значение свойства ImageId.</param>
        /// <param name="isWarranty">Исходное значение свойства IsWarranty.</param>
        /// <param name="warranty">Исходное значение свойства Warranty.</param>
        /// <param name="status">Исходное значение свойства Status.</param>
        public static Goods CreateGoods(global::System.Int32 id, global::System.String name, global::System.String article, global::System.Int32 categoryId, global::System.String shortInformation, global::System.String fullInformation, global::System.Decimal purchasePrice, global::System.Decimal maxPrice, global::System.Decimal middlePrice, global::System.Decimal minPrie, global::System.Int32 count, global::System.Int32 imageId, global::System.Boolean isWarranty, global::System.Int16 warranty, global::System.Int32 status)
        {
            Goods goods = new Goods();
            goods.Id = id;
            goods.Name = name;
            goods.Article = article;
            goods.CategoryId = categoryId;
            goods.ShortInformation = shortInformation;
            goods.FullInformation = fullInformation;
            goods.PurchasePrice = purchasePrice;
            goods.MaxPrice = maxPrice;
            goods.MiddlePrice = middlePrice;
            goods.MinPrie = minPrie;
            goods.Count = count;
            goods.ImageId = imageId;
            goods.IsWarranty = isWarranty;
            goods.Warranty = warranty;
            goods.Status = status;
            return goods;
        }

        #endregion

        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Article
        {
            get
            {
                return _Article;
            }
            set
            {
                OnArticleChanging(value);
                ReportPropertyChanging("Article");
                _Article = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Article");
                OnArticleChanged();
            }
        }
        private global::System.String _Article;
        partial void OnArticleChanging(global::System.String value);
        partial void OnArticleChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CategoryId
        {
            get
            {
                return _CategoryId;
            }
            set
            {
                OnCategoryIdChanging(value);
                ReportPropertyChanging("CategoryId");
                _CategoryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CategoryId");
                OnCategoryIdChanged();
            }
        }
        private global::System.Int32 _CategoryId;
        partial void OnCategoryIdChanging(global::System.Int32 value);
        partial void OnCategoryIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ShortInformation
        {
            get
            {
                return _ShortInformation;
            }
            set
            {
                OnShortInformationChanging(value);
                ReportPropertyChanging("ShortInformation");
                _ShortInformation = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ShortInformation");
                OnShortInformationChanged();
            }
        }
        private global::System.String _ShortInformation;
        partial void OnShortInformationChanging(global::System.String value);
        partial void OnShortInformationChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FullInformation
        {
            get
            {
                return _FullInformation;
            }
            set
            {
                OnFullInformationChanging(value);
                ReportPropertyChanging("FullInformation");
                _FullInformation = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FullInformation");
                OnFullInformationChanged();
            }
        }
        private global::System.String _FullInformation;
        partial void OnFullInformationChanging(global::System.String value);
        partial void OnFullInformationChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PurchasePrice
        {
            get
            {
                return _PurchasePrice;
            }
            set
            {
                OnPurchasePriceChanging(value);
                ReportPropertyChanging("PurchasePrice");
                _PurchasePrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PurchasePrice");
                OnPurchasePriceChanged();
            }
        }
        private global::System.Decimal _PurchasePrice;
        partial void OnPurchasePriceChanging(global::System.Decimal value);
        partial void OnPurchasePriceChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MaxPrice
        {
            get
            {
                return _MaxPrice;
            }
            set
            {
                OnMaxPriceChanging(value);
                ReportPropertyChanging("MaxPrice");
                _MaxPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxPrice");
                OnMaxPriceChanged();
            }
        }
        private global::System.Decimal _MaxPrice;
        partial void OnMaxPriceChanging(global::System.Decimal value);
        partial void OnMaxPriceChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MiddlePrice
        {
            get
            {
                return _MiddlePrice;
            }
            set
            {
                OnMiddlePriceChanging(value);
                ReportPropertyChanging("MiddlePrice");
                _MiddlePrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MiddlePrice");
                OnMiddlePriceChanged();
            }
        }
        private global::System.Decimal _MiddlePrice;
        partial void OnMiddlePriceChanging(global::System.Decimal value);
        partial void OnMiddlePriceChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MinPrie
        {
            get
            {
                return _MinPrie;
            }
            set
            {
                OnMinPrieChanging(value);
                ReportPropertyChanging("MinPrie");
                _MinPrie = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MinPrie");
                OnMinPrieChanged();
            }
        }
        private global::System.Decimal _MinPrie;
        partial void OnMinPrieChanging(global::System.Decimal value);
        partial void OnMinPrieChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Count
        {
            get
            {
                return _Count;
            }
            set
            {
                OnCountChanging(value);
                ReportPropertyChanging("Count");
                _Count = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Count");
                OnCountChanged();
            }
        }
        private global::System.Int32 _Count;
        partial void OnCountChanging(global::System.Int32 value);
        partial void OnCountChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ImageId
        {
            get
            {
                return _ImageId;
            }
            set
            {
                OnImageIdChanging(value);
                ReportPropertyChanging("ImageId");
                _ImageId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ImageId");
                OnImageIdChanged();
            }
        }
        private global::System.Int32 _ImageId;
        partial void OnImageIdChanging(global::System.Int32 value);
        partial void OnImageIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsWarranty
        {
            get
            {
                return _IsWarranty;
            }
            set
            {
                OnIsWarrantyChanging(value);
                ReportPropertyChanging("IsWarranty");
                _IsWarranty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsWarranty");
                OnIsWarrantyChanged();
            }
        }
        private global::System.Boolean _IsWarranty;
        partial void OnIsWarrantyChanging(global::System.Boolean value);
        partial void OnIsWarrantyChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Warranty
        {
            get
            {
                return _Warranty;
            }
            set
            {
                OnWarrantyChanging(value);
                ReportPropertyChanging("Warranty");
                _Warranty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Warranty");
                OnWarrantyChanged();
            }
        }
        private global::System.Int16 _Warranty;
        partial void OnWarrantyChanging(global::System.Int16 value);
        partial void OnWarrantyChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();

        #endregion

    
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="uh252489_dbModel", Name="Orders")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Orders : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта Orders.
        /// </summary>
        /// <param name="id">Исходное значение свойства Id.</param>
        /// <param name="deliveryTypeId">Исходное значение свойства DeliveryTypeId.</param>
        /// <param name="orderStatusId">Исходное значение свойства OrderStatusId.</param>
        /// <param name="paymentTypeId">Исходное значение свойства PaymentTypeId.</param>
        /// <param name="transporterTypeId">Исходное значение свойства TransporterTypeId.</param>
        public static Orders CreateOrders(global::System.Int32 id, global::System.Byte deliveryTypeId, global::System.Byte orderStatusId, global::System.Int16 paymentTypeId, global::System.Int16 transporterTypeId)
        {
            Orders orders = new Orders();
            orders.Id = id;
            orders.DeliveryTypeId = deliveryTypeId;
            orders.OrderStatusId = orderStatusId;
            orders.PaymentTypeId = paymentTypeId;
            orders.TransporterTypeId = transporterTypeId;
            return orders;
        }

        #endregion

        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> OrderNumber1C
        {
            get
            {
                return _OrderNumber1C;
            }
            set
            {
                OnOrderNumber1CChanging(value);
                ReportPropertyChanging("OrderNumber1C");
                _OrderNumber1C = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderNumber1C");
                OnOrderNumber1CChanged();
            }
        }
        private Nullable<global::System.Int64> _OrderNumber1C;
        partial void OnOrderNumber1CChanging(Nullable<global::System.Int64> value);
        partial void OnOrderNumber1CChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerName
        {
            get
            {
                return _CustomerName;
            }
            set
            {
                OnCustomerNameChanging(value);
                ReportPropertyChanging("CustomerName");
                _CustomerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustomerName");
                OnCustomerNameChanged();
            }
        }
        private global::System.String _CustomerName;
        partial void OnCustomerNameChanging(global::System.String value);
        partial void OnCustomerNameChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private Nullable<global::System.Int32> _UserId;
        partial void OnUserIdChanging(Nullable<global::System.Int32> value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneNumber
        {
            get
            {
                return _PhoneNumber;
            }
            set
            {
                OnPhoneNumberChanging(value);
                ReportPropertyChanging("PhoneNumber");
                _PhoneNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhoneNumber");
                OnPhoneNumberChanged();
            }
        }
        private global::System.String _PhoneNumber;
        partial void OnPhoneNumberChanging(global::System.String value);
        partial void OnPhoneNumberChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> OrderDate
        {
            get
            {
                return _OrderDate;
            }
            set
            {
                OnOrderDateChanging(value);
                ReportPropertyChanging("OrderDate");
                _OrderDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderDate");
                OnOrderDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _OrderDate;
        partial void OnOrderDateChanging(Nullable<global::System.DateTime> value);
        partial void OnOrderDateChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DeliveryDate
        {
            get
            {
                return _DeliveryDate;
            }
            set
            {
                OnDeliveryDateChanging(value);
                ReportPropertyChanging("DeliveryDate");
                _DeliveryDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeliveryDate");
                OnDeliveryDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _DeliveryDate;
        partial void OnDeliveryDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDeliveryDateChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte DeliveryTypeId
        {
            get
            {
                return _DeliveryTypeId;
            }
            set
            {
                OnDeliveryTypeIdChanging(value);
                ReportPropertyChanging("DeliveryTypeId");
                _DeliveryTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeliveryTypeId");
                OnDeliveryTypeIdChanged();
            }
        }
        private global::System.Byte _DeliveryTypeId;
        partial void OnDeliveryTypeIdChanging(global::System.Byte value);
        partial void OnDeliveryTypeIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte OrderStatusId
        {
            get
            {
                return _OrderStatusId;
            }
            set
            {
                OnOrderStatusIdChanging(value);
                ReportPropertyChanging("OrderStatusId");
                _OrderStatusId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrderStatusId");
                OnOrderStatusIdChanged();
            }
        }
        private global::System.Byte _OrderStatusId;
        partial void OnOrderStatusIdChanging(global::System.Byte value);
        partial void OnOrderStatusIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 PaymentTypeId
        {
            get
            {
                return _PaymentTypeId;
            }
            set
            {
                OnPaymentTypeIdChanging(value);
                ReportPropertyChanging("PaymentTypeId");
                _PaymentTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PaymentTypeId");
                OnPaymentTypeIdChanged();
            }
        }
        private global::System.Int16 _PaymentTypeId;
        partial void OnPaymentTypeIdChanging(global::System.Int16 value);
        partial void OnPaymentTypeIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 TransporterTypeId
        {
            get
            {
                return _TransporterTypeId;
            }
            set
            {
                OnTransporterTypeIdChanging(value);
                ReportPropertyChanging("TransporterTypeId");
                _TransporterTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TransporterTypeId");
                OnTransporterTypeIdChanged();
            }
        }
        private global::System.Int16 _TransporterTypeId;
        partial void OnTransporterTypeIdChanging(global::System.Int16 value);
        partial void OnTransporterTypeIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();

        #endregion

    
    }

    #endregion

    
}
>>>>>>> Partial Orders
